//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTN {
    using System;
    using FTN;
    
    
    /// Represents a single wire of an alternating current line segment.
    public class ACLineSegmentPhase : PowerSystemResource {
        
        /// The line segment to which the phase belongs.
        private ACLineSegment cim_ACLineSegment;
        
        private const bool isACLineSegmentMandatory = false;
        
        private const string _ACLineSegmentPrefix = "cim";
        
        /// The phase connection of the wire at both ends.
        private SinglePhaseKind? cim_phase;
        
        private const bool isPhaseMandatory = true;
        
        private const string _phasePrefix = "cim";
        
        public virtual ACLineSegment ACLineSegment {
            get {
                return this.cim_ACLineSegment;
            }
            set {
                this.cim_ACLineSegment = value;
            }
        }
        
        public virtual bool ACLineSegmentHasValue {
            get {
                return this.cim_ACLineSegment != null;
            }
        }
        
        public static bool IsACLineSegmentMandatory {
            get {
                return isACLineSegmentMandatory;
            }
        }
        
        public static string ACLineSegmentPrefix {
            get {
                return _ACLineSegmentPrefix;
            }
        }
        
        public virtual SinglePhaseKind Phase {
            get {
                return this.cim_phase.GetValueOrDefault();
            }
            set {
                this.cim_phase = value;
            }
        }
        
        public virtual bool PhaseHasValue {
            get {
                return this.cim_phase != null;
            }
        }
        
        public static bool IsPhaseMandatory {
            get {
                return isPhaseMandatory;
            }
        }
        
        public static string PhasePrefix {
            get {
                return _phasePrefix;
            }
        }
    }
}
