//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTN {
    using System;
    using FTN;
    
    
    /// This class represents the zero sequence line mutual coupling.
    public class MutualCoupling : IdentifiedObject {
        
        /// Zero sequence mutual coupling shunt (charging) susceptance, uniformly distributed, of the entire line section.
        private System.Single? cim_b0ch;
        
        private const bool isB0chMandatory = true;
        
        private const string _b0chPrefix = "cim";
        
        /// Distance to the start of the coupled region from the first line's terminal having sequence number equal to 1.
        private System.Single? cim_distance11;
        
        private const bool isDistance11Mandatory = true;
        
        private const string _distance11Prefix = "cim";
        
        /// Distance to the end of the coupled region from the first line's terminal with sequence number equal to 1.
        private System.Single? cim_distance12;
        
        private const bool isDistance12Mandatory = true;
        
        private const string _distance12Prefix = "cim";
        
        /// Distance to the start of coupled region from the second line's terminal with sequence number equal to 1.
        private System.Single? cim_distance21;
        
        private const bool isDistance21Mandatory = true;
        
        private const string _distance21Prefix = "cim";
        
        /// Distance to the end of coupled region from the second line's terminal with squence number equal to 1.
        private System.Single? cim_distance22;
        
        private const bool isDistance22Mandatory = true;
        
        private const string _distance22Prefix = "cim";
        
        /// The starting terminal for the calculation of distances along the first branch of the mutual coupling.  Normally MutualCoupling would only be used for terminals of AC line segments.  The first and second terminals of a mutual coupling should point to different AC line segments.
        private Terminal cim_First_Terminal;
        
        private const bool isFirst_TerminalMandatory = false;
        
        private const string _First_TerminalPrefix = "cim";
        
        /// Zero sequence mutual coupling shunt (charging) conductance, uniformly distributed, of the entire line section.
        private System.Single? cim_g0ch;
        
        private const bool isG0chMandatory = true;
        
        private const string _g0chPrefix = "cim";
        
        /// Zero sequence branch-to-branch mutual impedance coupling, resistance.
        private System.Single? cim_r0;
        
        private const bool isR0Mandatory = true;
        
        private const string _r0Prefix = "cim";
        
        /// The starting terminal for the calculation of distances along the second branch of the mutual coupling.
        private Terminal cim_Second_Terminal;
        
        private const bool isSecond_TerminalMandatory = false;
        
        private const string _Second_TerminalPrefix = "cim";
        
        /// Zero sequence branch-to-branch mutual impedance coupling, reactance.
        private System.Single? cim_x0;
        
        private const bool isX0Mandatory = true;
        
        private const string _x0Prefix = "cim";
        
        public virtual float B0ch {
            get {
                return this.cim_b0ch.GetValueOrDefault();
            }
            set {
                this.cim_b0ch = value;
            }
        }
        
        public virtual bool B0chHasValue {
            get {
                return this.cim_b0ch != null;
            }
        }
        
        public static bool IsB0chMandatory {
            get {
                return isB0chMandatory;
            }
        }
        
        public static string B0chPrefix {
            get {
                return _b0chPrefix;
            }
        }
        
        public virtual float Distance11 {
            get {
                return this.cim_distance11.GetValueOrDefault();
            }
            set {
                this.cim_distance11 = value;
            }
        }
        
        public virtual bool Distance11HasValue {
            get {
                return this.cim_distance11 != null;
            }
        }
        
        public static bool IsDistance11Mandatory {
            get {
                return isDistance11Mandatory;
            }
        }
        
        public static string Distance11Prefix {
            get {
                return _distance11Prefix;
            }
        }
        
        public virtual float Distance12 {
            get {
                return this.cim_distance12.GetValueOrDefault();
            }
            set {
                this.cim_distance12 = value;
            }
        }
        
        public virtual bool Distance12HasValue {
            get {
                return this.cim_distance12 != null;
            }
        }
        
        public static bool IsDistance12Mandatory {
            get {
                return isDistance12Mandatory;
            }
        }
        
        public static string Distance12Prefix {
            get {
                return _distance12Prefix;
            }
        }
        
        public virtual float Distance21 {
            get {
                return this.cim_distance21.GetValueOrDefault();
            }
            set {
                this.cim_distance21 = value;
            }
        }
        
        public virtual bool Distance21HasValue {
            get {
                return this.cim_distance21 != null;
            }
        }
        
        public static bool IsDistance21Mandatory {
            get {
                return isDistance21Mandatory;
            }
        }
        
        public static string Distance21Prefix {
            get {
                return _distance21Prefix;
            }
        }
        
        public virtual float Distance22 {
            get {
                return this.cim_distance22.GetValueOrDefault();
            }
            set {
                this.cim_distance22 = value;
            }
        }
        
        public virtual bool Distance22HasValue {
            get {
                return this.cim_distance22 != null;
            }
        }
        
        public static bool IsDistance22Mandatory {
            get {
                return isDistance22Mandatory;
            }
        }
        
        public static string Distance22Prefix {
            get {
                return _distance22Prefix;
            }
        }
        
        public virtual Terminal First_Terminal {
            get {
                return this.cim_First_Terminal;
            }
            set {
                this.cim_First_Terminal = value;
            }
        }
        
        public virtual bool First_TerminalHasValue {
            get {
                return this.cim_First_Terminal != null;
            }
        }
        
        public static bool IsFirst_TerminalMandatory {
            get {
                return isFirst_TerminalMandatory;
            }
        }
        
        public static string First_TerminalPrefix {
            get {
                return _First_TerminalPrefix;
            }
        }
        
        public virtual float G0ch {
            get {
                return this.cim_g0ch.GetValueOrDefault();
            }
            set {
                this.cim_g0ch = value;
            }
        }
        
        public virtual bool G0chHasValue {
            get {
                return this.cim_g0ch != null;
            }
        }
        
        public static bool IsG0chMandatory {
            get {
                return isG0chMandatory;
            }
        }
        
        public static string G0chPrefix {
            get {
                return _g0chPrefix;
            }
        }
        
        public virtual float R0 {
            get {
                return this.cim_r0.GetValueOrDefault();
            }
            set {
                this.cim_r0 = value;
            }
        }
        
        public virtual bool R0HasValue {
            get {
                return this.cim_r0 != null;
            }
        }
        
        public static bool IsR0Mandatory {
            get {
                return isR0Mandatory;
            }
        }
        
        public static string R0Prefix {
            get {
                return _r0Prefix;
            }
        }
        
        public virtual Terminal Second_Terminal {
            get {
                return this.cim_Second_Terminal;
            }
            set {
                this.cim_Second_Terminal = value;
            }
        }
        
        public virtual bool Second_TerminalHasValue {
            get {
                return this.cim_Second_Terminal != null;
            }
        }
        
        public static bool IsSecond_TerminalMandatory {
            get {
                return isSecond_TerminalMandatory;
            }
        }
        
        public static string Second_TerminalPrefix {
            get {
                return _Second_TerminalPrefix;
            }
        }
        
        public virtual float X0 {
            get {
                return this.cim_x0.GetValueOrDefault();
            }
            set {
                this.cim_x0 = value;
            }
        }
        
        public virtual bool X0HasValue {
            get {
                return this.cim_x0 != null;
            }
        }
        
        public static bool IsX0Mandatory {
            get {
                return isX0Mandatory;
            }
        }
        
        public static string X0Prefix {
            get {
                return _x0Prefix;
            }
        }
    }
}
