//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTN {
    using System;
    
    
    public enum SinglePhaseKind {
        
        /// Phase A.
        A,
        
        /// Phase B.
        B,
        
        /// Phase C.
        C,
        
        /// Neutral.
        N,
        
        /// Secondary phase 1.
        s1,
        
        /// Secondary phase 2.
        s2,
    }
}
